// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1hrotL6GuSb55V74YGB4Jlwmt8rslH4',
    appId: '1:630812556650:web:46d4941c6d2c0d4bf87913',
    messagingSenderId: '630812556650',
    projectId: 'electro-app-fc2db',
    authDomain: 'electro-app-fc2db.firebaseapp.com',
    storageBucket: 'electro-app-fc2db.firebasestorage.app',
    measurementId: 'G-4JXECPBY85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnsfJdRM8z-gYBftipRyifme-pSxKcVjk',
    appId: '1:630812556650:android:6509056a6af022e0f87913',
    messagingSenderId: '630812556650',
    projectId: 'electro-app-fc2db',
    storageBucket: 'electro-app-fc2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3mLNmHohGnjRcZG87J7p6LMrHBE-kZig',
    appId: '1:630812556650:ios:c487af19762e4c37f87913',
    messagingSenderId: '630812556650',
    projectId: 'electro-app-fc2db',
    storageBucket: 'electro-app-fc2db.firebasestorage.app',
    iosBundleId: 'com.example.electrocart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3mLNmHohGnjRcZG87J7p6LMrHBE-kZig',
    appId: '1:630812556650:ios:c487af19762e4c37f87913',
    messagingSenderId: '630812556650',
    projectId: 'electro-app-fc2db',
    storageBucket: 'electro-app-fc2db.firebasestorage.app',
    iosBundleId: 'com.example.electrocart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw1hrotL6GuSb55V74YGB4Jlwmt8rslH4',
    appId: '1:630812556650:web:7c013aaa115ea7d6f87913',
    messagingSenderId: '630812556650',
    projectId: 'electro-app-fc2db',
    authDomain: 'electro-app-fc2db.firebaseapp.com',
    storageBucket: 'electro-app-fc2db.firebasestorage.app',
    measurementId: 'G-3PS1TK1GBL',
  );
}
